CREATE TABLE WORD (
	id BIGINT NOT NULL,
	word VARCHAR(255),
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE MEANING (
	id BIGINT NOT NULL,
	definition VARCHAR(255),
	example VARCHAR(255),
	partOfSpeach VARCHAR(255),
	word_fk BIGINT,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE INDEX FK62B6BDDDE7690523 ON MEANING (word_fk ASC);